@UTILTEST @DATAMAPPER
Feature: DataMapper - Map And Flatten Objects
    As a developer
    I want to test the DataMapper utility method mapAndflattenObjectData
    So that I can ensure the correct key-value pairs or property paths object are generated.

    Scenario Outline: DATAMAPPER-FLATTEN-OBJECTS-001 - DataMapper method flattens nested object to key-value pairs or property paths object
        Given an input object with values:
            """
            <inputObject>
            """
        When I call the DataMapper mapAndflattenObjectData method with asObject set to "<asObject>"
        Then the flattened object as a StringArray result should be:
            """
            <expectedResult>
            """

        Examples:
            | inputObject                                                                                                                                                                                                                                                                                                                 | asObject | expectedResult                                                                                                                                                                                                                                                                                                                                                                                   |
            | {"Address": {"Street": "123 Main St", "City": "New York", "PostalCode": "GL1 1LL"}}                                                                                                                                                                                                                                         | false    | [{"path":"Address.Street","value":"123 Main St"},{"path":"Address.City","value":"New York"},{"path":"Address.PostalCode","value":"GL1 1LL"}]                                                                                                                                                                                                                                                     |
            | {"PersonalDetails": {"FirstName": "Alice", "LastName": "Johnson", "Contacts": {"Email": "alice@example.com", "Phone": "555-1234"}}}                                                                                                                                                                                         | false    | [{"path":"PersonalDetails.FirstName","value":"Alice"},{"path":"PersonalDetails.LastName","value":"Johnson"},{"path":"PersonalDetails.Contacts.Email","value":"alice@example.com"},{"path":"PersonalDetails.Contacts.Phone","value":"555-1234"}]                                                                                                                                                  |
            | {"Inventory": [{"Item": "Laptop", "Quantity": 2, "Specs": {"RAM": "16GB", "Storage": "512GB"}}, {"Item": "Monitor", "Quantity": 1, "Specs": {"Resolution": "4K", "Size": "27 inches"}}]}                                                                                                                                    | false    | [{"path":"Inventory.1.Item","value":"Laptop"},{"path":"Inventory.1.Quantity","value":2},{"path":"Inventory.1.Specs.RAM","value":"16GB"},{"path":"Inventory.1.Specs.Storage","value":"512GB"},{"path":"Inventory.2.Item","value":"Monitor"},{"path":"Inventory.2.Quantity","value":1},{"path":"Inventory.2.Specs.Resolution","value":"4K"},{"path":"Inventory.2.Specs.Size","value":"27 inches"}] |
            | {"EmptyArray": []}                                                                                                                                                                                                                                                                                                          | false    | []                                                                                                                                                                                                                                                                                                                                                                                               |
            | {}                                                                                                                                                                                                                                                                                                                          | false    | []                                                                                                                                                                                                                                                                                                                                                                                               |
            | {"NestedArray": {"Teams": [{"Name": "Team A", "Score": 80}, {"Name": "Team B", "Score": 90}]}}                                                                                                                                                                                                                              | false    | [{"path":"NestedArray.Teams.1.Name","value":"Team A"},{"path":"NestedArray.Teams.1.Score","value":80},{"path":"NestedArray.Teams.2.Name","value":"Team B"},{"path":"NestedArray.Teams.2.Score","value":90}]                                                                                                                                                                                      |
            | {"Employee": {"Name": "John", "ID": 123}, "Department": "HR"}                                                                                                                                                                                                                                                               | false    | [{"path":"Employee.Name","value":"John"},{"path":"Employee.ID","value":123},{"path":"Department","value":"HR"}]                                                                                                                                                                                                                                                                                  |
            | {"Employee": {"Name": "John", "ID": 123}, "Department": "HR"}                                                                                                                                                                                                                                                               | true     | {"Employee.Name": "John","Employee.ID": 123,"Department": "HR"}                                                                                                                                                                                                                                                                                                                                  |
            | {"Skills":[{"Type":"Programming","Level":"Expert"},{"Type":"Design","Level":"Intermediate"}]}                                                                                                                                                                                                                               | true     | {"Skills.1.Type":"Programming","Skills.1.Level":"Expert","Skills.2.Type":"Design","Skills.2.Level":"Intermediate"}                                                                                                                                                                                                                                                                               |
            | {"AddressLines":["123 High Street","City","Country"],"PostCode":"AB12CD"}                                                                                                                                                                                                                                                   | true     | {"AddressLines.1": "123 High Street","AddressLines.2": "City","AddressLines.3": "Country","PostCode": "AB12CD"}                                                                                                                                                                                                                                                                                  |
            | {"AddressLines":["123 High Street","City","Country"],"PostCode":"AB12CD"}                                                                                                                                                                                                                                                   | false    | [{"path": "AddressLines.1","value": "123 High Street"},{"path": "AddressLines.2","value":"City" },{"path":"AddressLines.3","value":"Country"},{"path": "PostCode","value": "AB12CD"}]                                                                                                                                                                                                            |
            | {"PID":"12345","Scheme":"Scholarship2025","Profile":{"Forenames":"John","Initials":"J","Surname":"Doe","Email":"john.doe@example.com","Gender":"Male","DateOfBirth":"1990-01-01","HomeNumber":"1234567890","MobileNumber":"0987654321"},"PostCode":"AB12CD"}                                                                | true     | {"PID":"12345","Scheme":"Scholarship2025","Profile.Forenames":"John","Profile.Initials":"J","Profile.Surname":"Doe","Profile.Email":"john.doe@example.com","Profile.Gender":"Male","Profile.DateOfBirth":"1990-01-01","Profile.HomeNumber":"1234567890","Profile.MobileNumber":"0987654321","PostCode":"AB12CD"}                                                                                 |
            | {"Profile":{"Forenames":"Alice","Initials":"A","Surname":"Smith","Email":"alice.smith@example.com","Gender":"Female","DateOfBirth":"1985-05-15","HomeNumber":"1122334455","MobileNumber":"9988776655"},"PostCode":"XY99ZZ","FeeType":"Partial","FeePaid":"300","TotalFee":"500","PaymentAmount":"300","RefundAmount":"200"} | true     | {"Profile.Forenames":"Alice","Profile.Initials":"A","Profile.Surname":"Smith","Profile.Email":"alice.smith@example.com","Profile.Gender":"Female","Profile.DateOfBirth":"1985-05-15","Profile.HomeNumber":"1122334455","Profile.MobileNumber":"9988776655","PostCode":"XY99ZZ","FeeType":"Partial","FeePaid":"300","TotalFee":"500","PaymentAmount":"300","RefundAmount":"200"}                  |
            | [{"User":{"Profile":{"Name":"Alice","Age":30},"Account":{"ID":123}},"Status":"Active"},{"User":{"Profile":{"Name":"Bob","Age":25},"Account":{"ID":456}},"Status":"Inactive"}]                                                                                                                                               | true     | {"0.User.Profile.Name":"Alice","0.User.Profile.Age":30,"0.User.Account.ID":123,"0.Status":"Active","1.User.Profile.Name":"Bob","1.User.Profile.Age":25,"1.User.Account.ID":456,"1.Status":"Inactive"}                                                                                                                                                                                            |
            | [{"Title":"Degree 1","Year":"2020"},{"Title":"Degree 2","Year":"2021"}]                                                                                                                                                                                                                                                     | false    | [{"path": "0.Title","value": "Degree 1"},{"path": "0.Year","value": "2020"},{"path": "1.Title","value": "Degree 2"},{"path":"1.Year","value": "2021"}]                                                                                                                                                                                                                                           |